export const ERROR_CODES = {
  // Auth
  AUTH_UNAUTHORIZED: 'AUTH_001',
  AUTH_FORBIDDEN: 'AUTH_002',
  AUTH_TOKEN_EXPIRED: 'AUTH_003',
  AUTH_INVALID_TOKEN: 'AUTH_004',
  AUTH_INVALID_CREDENTIALS: 'AUTH_005',

  // User
  USER_NOT_FOUND: 'USER_001',
  USER_ALREADY_EXISTS: 'USER_002',
  USER_INVALID_PASSWORD: 'USER_003',

  // Post
  POST_NOT_FOUND: 'POST_001',
  POST_ALREADY_EXISTS: 'POST_002',

  // File
  FILE_INVALID_TYPE: 'FILE_001',
  FILE_TOO_LARGE: 'FILE_002',
  FILE_UPLOAD_FAILED: 'FILE_003',

  // Validation
  VALIDATION_FAILED: 'VAL_001',

  // Generic
  INTERNAL_ERROR: 'SRV_001',
  NOT_FOUND: 'SRV_002',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
